### PR TITLE
Fix on load module utils

### PR DESCRIPTION
**Pull request by cassiothadeu**
When installed yeoman generator and use with the command yo hapi-api-stack the error occurs.

image

### CODE REVIEW

**Comment by lsilva-kununu** [comment]
:(

**Comment by lsilva-kununu** [comment]
Please merge it.

**Comment by victorsosa** [comment]
this is the fix for issue #3

**Comment by jagged3dge** [comment]
I'm not sure how this fix is working for you guys. For me, the `utils` directory is just doesn't exist in the global `node_modules/generator-hapi-api-stack` directory after installing via `npm i -g generator-hapi-api-stack`. The fix for me was to manually copy the utils directory to it :disappointed:

**Comment by franzip** [comment]
@cassiothadeu Thanks for the PR and sorry for the super late reply.

Turns out the issue was that the `utils` folder was not included in the package.json under the `files` array property

**Pull request closed without merging**
